spring:
  application:
    name: secure-task-manager-api

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task-manager?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/realm-demo
          jwk-set-uri: http://localhost:9090/realms/realm-demo/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate: INFO

jwt:
  auth:
    converter:
      resource-id: demo
      principle-attribute: preferred_username